environment:

  matrix:
    - PYTHON: "C:\\Miniconda37-x64"
      LICENSE: 1
      DEPEND_SOURCE: 1
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CI_PROVIDER: 2  # Travis+Appveyor
      RTD: 1

    - PYTHON: "C:\\Miniconda38-x64"
      LICENSE: 2
      DEPEND_SOURCE: 2
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      CI_PROVIDER: 2
      RTD: 2

    - PYTHON: "C:\\Python37-x64"
      LICENSE: 1
      DEPEND_SOURCE: 3
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CI_PROVIDER: 2
      RTD: 2



install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    # Install a few requirements
  - pip install pyyaml cookiecutter

    # Dont ask
  - git config --global user.email "monster@cookie.com"
  - git config --global user.name "Cookie Monster"
  - git config --global core.autocrlf true

    # Build out the cookiecutter from settings
  - python tests/setup_cookiecutter.py default_project %LICENSE% %DEPEND_SOURCE% %CI_PROVIDER% %RTD%

    # Change into new project directory
  - ps: cd default_project

    # Run appveyor YAML
  - python ../tests/run_yaml.py appveyor.yml install install.appveyor.bat
  - .\install.appveyor.bat

build: false

test_script:
  - pip install pyyaml
  - python ../tests/run_yaml.py appveyor.yml test_script script.appveyor.bat
  - .\script.appveyor.bat
