environment:

  matrix:
  {%- if (cookiecutter.dependency_source == 'Prefer conda-forge over the default anaconda channel with pip fallback' or cookiecutter.dependency_source == 'Prefer default anaconda channel with pip fallback') %}
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
  {% elif cookiecutter.dependency_source == 'Dependencies from pip only (no conda)' %}
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
  {% endif %}

install:
    # Make sure pip is around
  - python -m ensurepip
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  {% if (cookiecutter.dependency_source == 'Prefer conda-forge over the default anaconda channel with pip fallback' or cookiecutter.dependency_source == 'Prefer default anaconda channel with pip fallback') %}
  {%- if cookiecutter.dependency_source == 'Prefer conda-forge over the default anaconda channel with pip fallback' %}
    # Add conda-forge channel
  - conda config --add channels conda-forge
  {% endif %}

    # Always run commands without asking
  - conda config --set always_yes yes

    # Try to update conda first to avoid odd dependency clashes
  - conda update --all

    # Create test environment for package
  - python devtools\\scripts\\create_conda_env.py -n=test -p=%PYTHON_VERSION% devtools\\conda-envs\\test_env.yaml

    # Activate the test environment
  - activate test

    # Build and install package
  - python setup.py develop --no-deps

  {% elif cookiecutter.dependency_source == 'Dependencies from pip only (no conda)' %}
    # Install the package locally
  - pip install --upgrade pip setuptools
  - pip install pytest pytest-cov codecov
  - pip install -e .
  {% endif %}
build: false

test_script:
  - pytest -v --cov={{cookiecutter.repo_name}} {{cookiecutter.repo_name}}\\tests

on_success:
  - codecov
